apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: al9t7swbk-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/al9t7swbk-java-springboot-gitops