apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: al9t7swbk-java-springboot
  janus-idp.io/tekton: al9t7swbk-java-springboot
  backstage.io/kubernetes-id: al9t7swbk-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: al9t7swbk-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
